// Generated by CoffeeScript 1.7.1
(function() {
  var __slice = [].slice;

  (function($) {
    var $block, $blockContent, $blockh1, $blockh2, $blockp, $body, $header, $slider, $sliderUi, $slider_, checkSlideScheme, doSlider, mobile_, options, optionsFinal, optionsFirst, properties, resetBody, setBody, skipfade;
    mobile_ = $(window).width() < 950;
    $body = $('body');
    $slider = $('#slider');
    $header = $('#header');
    $slider_ = $slider.length;
    setBody = function() {
      $body.css('position', 'fixed');
      return $body.addClass('fade-in-progress');
    };
    resetBody = function() {
      $body.css('position', 'static');
      return $body.removeClass('fade-in-progress');
    };
    checkSlideScheme = function(slideNum) {
      var $current, slideImgBg_, slideScheme, uiScheme, uiShadows;
      slideNum--;
      $current = $('section[slidesjs-index="' + slideNum + '"]');
      slideScheme = $current.attr('data-slide-scheme');
      uiScheme = $header.attr('data-ui-scheme');
      if (slideScheme !== uiScheme) {
        $header.attr('data-ui-scheme', slideScheme);
        $slider.attr('data-ui-scheme', slideScheme);
      }
      slideImgBg_ = $current.hasClass('photo');
      uiShadows = $header.attr('data-img-background');
      if (slideImgBg_ !== uiShadows) {
        $header.attr('data-img-background', slideImgBg_.toString());
        $slider.attr('data-img-background', slideImgBg_.toString());
      }
      return slideNum;
    };
    skipfade = function() {
      var $elem, $selectors, _i, _len, _results;
      $selectors = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = $selectors.length; _i < _len; _i++) {
        $elem = $selectors[_i];
        console.log($elem);
        _results.push($elem.stop(true, true));
      }
      return _results;
    };
    doSlider = function($slider, duration) {
      var args;
      if (duration == null) {
        duration = 7500;
      }
      args = {
        width: $(window).width(),
        height: $(window).height(),
        pagination: {
          active: true
        },
        navigation: {
          active: false
        },
        play: {
          active: false,
          auto: true,
          interval: duration,
          restartDelay: 0,
          pauseOnClick: true
        },
        callback: {
          complete: function(slideNum) {
            return checkSlideScheme(slideNum);
          }
        }
      };
      if (!mobile_) {
        $slider.slidesjs(args);
      }
      return $slider;
    };
    properties = {
      opacity: 1
    };
    options = {
      duration: 1000
    };
    optionsFirst = {
      duration: 3000
    };
    optionsFinal = {
      duration: 1000,
      complete: resetBody
    };
    if ($slider_) {
      $block = $('#slider .block:first-of-type');
      if (!mobile_) {
        if ($block.hasClass('fade')) {
          setBody();
          $blockh1 = $('#slider .block:first-of-type h1');
          $blockh2 = $('#slider .block:first-of-type h2');
          $blockp = $('#slider .block:first-of-type .headers p');
          $blockContent = $('#slider .block:first-of-type .content');
          doSlider($slider, 15000);
          $sliderUi = $('#slider .slidesjs-pagination');
          $(document).click(function() {
            return skipfade([$blockh1, $blockh2, $blockp, $blockContent, $sliderUi, $header]);
          });
          $header.css('opacity', '0');
          $slider.css('opacity', '0');
          $blockh1.css('opacity', '0');
          $blockh2.css('opacity', '0');
          $blockp.css('opacity', '0');
          $blockContent.css('opacity', '0');
          $sliderUi.css('opacity', '0');
          $slider.animate(properties, optionsFirst);
          $blockh1.delay(3000).animate(properties, options);
          $blockh2.delay(5500).animate(properties, options);
          $blockp.delay(8500).animate(properties, options);
          $blockContent.delay(8500).animate(properties, options);
          $sliderUi.delay(8500).animate(properties, options);
          return $header.delay(8500).animate(properties, optionsFinal);
        } else {
          return doSlider($slider);
        }
      }
    } else {
      if (!mobile_) {
        $block = $('body .block:first-of-type');
        if ($block.hasClass('fade')) {
          setBody();
          $blockh1 = $('.block:first-of-type h1');
          $blockh2 = $('.block:first-of-type h2');
          $blockp = $('.block:first-of-type .headers p');
          $blockContent = $('.block:first-of-type .content');
          $(document).click(function() {
            return skipfade($blockh1, $blockh2, $blockp, $blockContent, $header);
          });
          $block.css('opacity', '0');
          $header.css('opacity', '0');
          $blockh1.css('opacity', '0');
          $blockh2.css('opacity', '0');
          $blockp.css('opacity', '0');
          $blockContent.css('opacity', '0');
          $block.animate(properties, optionsFirst);
          $blockh1.delay(3000).animate(properties, options);
          $blockh2.delay(5500).animate(properties, options);
          $blockp.delay(8500).animate(properties, options);
          $blockContent.delay(8500).animate(properties, options);
          return $header.delay(8500).animate(properties, optionsFinal);
        }
      }
    }
  })(jQuery);

}).call(this);
