// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $(function() {
      var $comReveal, $comTrigger, $window, mobile, width;
      $window = $(window);
      width = $window.width();
      mobile = width < 950;
      console.log('Present!');
      $comReveal = $('#reveal-comments');
      $comTrigger = $('#reveal-comments-a');
      if (mobile) {
        $comReveal.hide();
        $comTrigger.show();
      }
      $window.resize(function() {
        width = $window.width();
        mobile = width < 950;
        if (!$comTrigger.hasClass('active')) {
          if (mobile) {
            $comReveal.hide();
            return $comTrigger.show();
          } else {
            $comReveal.show();
            return $comTrigger.hide();
          }
        }
      });
      return $comTrigger.click(function() {
        $comTrigger.blur();
        $comTrigger.toggleClass('active');
        return $comReveal.slideToggle(250);
      });
    });
  })(jQuery);

}).call(this);
