// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    var $btn, $nav, $navM, checkDisplay, slideNav, width;
    $navM = $('#nav-mobile');
    $nav = $('#nav');
    $btn = $('#nav-mobile-reveal');
    width = $(window).width();
    checkDisplay = function() {
      width = $(window).width();
      console.log(width);
      if (width < 650) {
        $nav.hide();
        return $btn.show();
      } else if (width >= 650) {
        $nav.css({
          display: 'flex'
        });
        $navM.hide();
        return $btn.hide();
      }
    };
    checkDisplay();
    $(window).resize(checkDisplay);
    $navM.hide().addClass('collapsed');
    slideNav = function() {
      console.log('Fired');
      $btn.blur();
      if ($navM.hasClass('collapsed')) {
        $navM.removeClass('collapsed');
        $navM.addClass('opened');
        return $navM.slideDown(250);
      } else if ($navM.hasClass('opened')) {
        $navM.removeClass('opened');
        $navM.addClass('collapsed');
        return $navM.slideUp(250);
      }
    };
    return $btn.click(slideNav);
  })(jQuery);

}).call(this);
