// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $(function() {
      var $nav, $reveal, toggleNav;
      $nav = $('#n-mobile');
      $reveal = $('#n-reveal');
      $nav.hide();
      $nav.addClass('collapsed');
      toggleNav = function() {
        $reveal.blur();
        if ($nav.hasClass('collapsed')) {
          $nav.removeClass('collapsed');
          $nav.slideDown(250);
        } else {
          $nav.addClass('collapsed');
          $nav.slideUp(250);
        }
        return false;
      };
      return $reveal.click(toggleNav);
    });
  })(jQuery);

}).call(this);
