// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    return $(function() {
      var $header, $slider, $window, changeScheme, currentScheme, doSlider, findSlideSchemeById, mobile, sliderFinish, sliderInit, width;
      $window = $(window);
      width = $window.width();
      mobile = width < 650;
      $window.resize(function() {
        width = $window.width();
        return mobile = width < 650;
      });
      currentScheme = null;
      $slider = $('#slider');
      $header = $('#h');
      findSlideSchemeById = function(slideId) {
        slideId--;
        return $('#slider .slidesjs-slide[slidesjs-index="' + slideId.toString() + '"]').attr('data-scheme');
      };
      sliderInit = function(slideNum) {
        var scheme;
        scheme = findSlideSchemeById(slideNum);
        $header.addClass(scheme);
        $slider.addClass(scheme);
        return currentScheme = scheme;
      };
      changeScheme = function(newScheme) {
        $header.toggleClass('light');
        $header.toggleClass('dark');
        $slider.toggleClass('light');
        $slider.toggleClass('dark');
        if (currentScheme !== newScheme) {
          return currentScheme = newScheme;
        }
      };
      sliderFinish = function(slideNum) {
        var newScheme;
        newScheme = findSlideSchemeById(slideNum);
        return changeScheme(newScheme);
      };
      doSlider = function(interval) {
        var args;
        if (interval == null) {
          interval = 5000;
        }
        args = {
          width: width,
          height: $(window).height(),
          navigation: {
            active: false
          },
          pagination: {
            active: true,
            effect: "fade"
          },
          play: {
            active: false,
            effect: "fade",
            interval: interval,
            auto: true,
            pauseOnHover: false
          },
          fade: {
            speed: 10000,
            crossfade: true
          },
          callback: {
            loaded: sliderInit,
            complete: sliderFinish
          }
        };
        return $slider.slidesjs(args);
      };
      if (!mobile) {
        return doSlider();
      }
    });
  })(jQuery);

}).call(this);
